name: Deploy to GitHub Pages

permissions:
  contents: write
  pages: write
  id-token: write

on:
  push:
    branches:
      - main  # Change to your default branch if different
      - dev
  pull_request:
    branches:
      - main  # Change to your default branch if different
      - dev

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [18, 20, 22]  # Specify the Node.js versions you want to test

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
        with:
            persist-credentials: false

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: ${{ matrix.node-version }}

      - name: Install dependencies
        run: npm install

      - name: Build the project
        run: npm run build
      
      - name: Upload production-ready files
        uses: actions/upload-artifact@v2
        with:
          path: ./dist
          name: production-files
  deploy:
    name: Deploy
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Download artifact
        uses: actions/download-artifact@v3
        with:
            name: production-files
            path: ./dist
    
      - name: Deploy to GitHub Pages
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          branch: gh-pages
          folder: dist
          token: ${{ secrets.GITHUB_TOKEN }}  # Use PAT instead of GITHUB_TOKEN
          clean: true
          force: true